### ISSUE TITLE
Infinite loop if no articles are found

### ISSUE THREAD

**Issue by piperfw** [DavidMChan/ArXiV-Notify#2]
If a query produces no results (e.g. `KEYWORD=oqu` at the time of writing), `fetch_queries` repeats the search indefinitely and the program hangs.

The simple workaround is to put a break condition in this function e.g.
```
if not articles:
    do_continue = False
    break
```
Happy to make this a PR if that would be helpful.

**Comment by DavidMChan** [comment]
Thanks! Updated this!
